### ISSUE TITLE
Container crashes: Index out of range

### ISSUE THREAD

**Issue by djarotech** [cloud-ark/kubediscovery#48]
```
$ kubectl logs kubeplus-x968p kube-discovery-apiserver
I0408 21:04:24.318381       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0408 21:04:24.753634       1 plugins.go:158] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I0408 21:04:24.753821       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
W0408 21:04:24.754637       1 genericapiserver.go:319] Skipping API kubeplus.cloudark.io/v1 because it has no resources.
I0408 21:04:24.755025       1 serve.go:96] Serving securely on [::]:443
Custom Resource Kind:Recovery
panic: runtime error: index out of range

goroutine 2868 [running]:
github.com/cloud-ark/kubediscovery/pkg/discovery.readConfigMap(0x0, 0x0, 0x8, 0x1, 0x1, 0x26)
	/Users/dan/Desktop/goworkspace/src/github.com/cloud-ark/kubediscovery/pkg/discovery/operatordocs.go:219 +0x6c8
github.com/cloud-ark/kubediscovery/pkg/discovery.GetImplementationDetails(0xc002874747, 0x8, 0xc001d23168, 0x1, 0x1, 0x1e)
	/Users/dan/Desktop/goworkspace/src/github.com/cloud-ark/kubediscovery/pkg/discovery/operatordocs.go:118 +0x35e
github.com/cloud-ark/kubediscovery/pkg/apiserver.handleManPageEndpoint(0xc00278ac30, 0xc0026207e0)
	/Users/dan/Desktop/goworkspace/src/github.com/cloud-ark/kubediscovery/pkg/apiserver/apiserver.go:165 +0x114
github.com/cloud-ark/kubediscovery/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000872ea0, 0x7f3f5768fe38, 0xc000b44650, 0xc00025d900)
	/Users/dan/Desktop/goworkspace/src/github.com/cloud-ark/kubediscovery/vendor/github.com/emicklei/go-restful/container.go:277 +0x9a6
github.com/cloud-ark/kubediscovery/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc000872ea0, 0x7f3f5768fe38, 0xc000b44650, 0xc00025d900)
```
The container crashes, when I run this command. Probably Recovery kind IS somewhere in the data, because running an arbitrary kind actually does not produce this error. So it is not because the Kind is not found.
I was adding man pages for restic and I ran into this.

```
CRD Name List:[/crds/recoveries.stash.appscode.com /crds/repositories.stash.appscode.com /crds/restics.stash.appscode.com]:::: Implementation Details CMap: :::::::: Implementation Details CMap: :::::::: Implementation Details CMap: ::::
```

**Comment by djarotech** [comment]
Was able to get this to work, when I copied stash's CRDs into the helm folder.  Closing
